version: '3.8'
services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "SimuladorCredito2025!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped

  backend:
    build:
      context: ./SimuladorCredito.Api
    container_name: backendApi
    depends_on:
      - sqlserver
    environment:
      - TZ=America/Sao_Paulo
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8001:80"
    restart: on-failure

  frontend:
    build:
      context: ./SimuladorCredito.Web.App
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: on-failure

volumes:
  sql_data:
