// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimuladorCredito.Api.Data;

#nullable disable

namespace SimuladorCredito.Api.Migrations
{
    [DbContext(typeof(DbContextClass))]
    partial class DbContextClassModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("SimuladorCredito")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimuladorCredito.Api.Models.Entidades.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Produtos", "SimuladorCredito");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Financiamento de pessoas físicas",
                            Nome = "Financiamento",
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Sicoob Engecred Consignado",
                            Nome = "Sicoob Engecred Consignado",
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Empréstimo Pessoal de pessoas físicas",
                            Nome = "Empréstimo Pessoal",
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Imóveis de pessoas físicas",
                            Nome = "Imóveis",
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Financiamento de pessoas jurídicas",
                            Nome = "Financiamento",
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Crédito Rural",
                            Nome = "Crédito Rural",
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Empréstimo Pessoal de pessoas jurídicas",
                            Nome = "Empréstimo Pessoal",
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Imóveis de pessoas jurídicas",
                            Nome = "Imóveis",
                            TipoPessoa = 2
                        });
                });

            modelBuilder.Entity("SimuladorCredito.Api.Models.Entidades.Segmento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RendaMaxima")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RendaMinima")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Segmentos", "SimuladorCredito");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Segmento inicial para PF com renda até R$3.000",
                            Nome = "Start",
                            RendaMaxima = 3000.00m,
                            RendaMinima = 0.00m,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "PF com renda entre R$3.001 e R$10.000",
                            Nome = "Intermediário",
                            RendaMaxima = 10000.00m,
                            RendaMinima = 3000.01m,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "PF com renda acima de R$10.000",
                            Nome = "Premium",
                            RendaMinima = 10000.01m,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "PJ com renda até R$20.000",
                            Nome = "Empreendedor",
                            RendaMaxima = 20000.00m,
                            RendaMinima = 0.00m,
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "PJ com renda entre R$20.001 e R$100.000",
                            Nome = "Empresarial",
                            RendaMaxima = 100000.00m,
                            RendaMinima = 20000.01m,
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "PJ com renda acima de R$100.000",
                            Nome = "Corporativo",
                            RendaMinima = 100000.01m,
                            TipoPessoa = 2
                        });
                });

            modelBuilder.Entity("SimuladorCredito.Api.Models.Entidades.TaxaCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Modalidade")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("SegmentoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Taxa")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("SegmentoId");

                    b.ToTable("TaxasCredito", "SimuladorCredito");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 1,
                            ProdutoId = 1,
                            SegmentoId = 1,
                            Taxa = 0.10m,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 1,
                            ProdutoId = 1,
                            SegmentoId = 2,
                            Taxa = 0.09m,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 1,
                            ProdutoId = 1,
                            SegmentoId = 3,
                            Taxa = 0.08m,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 1,
                            ProdutoId = 3,
                            SegmentoId = 1,
                            Taxa = 0.09m,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 1,
                            ProdutoId = 3,
                            SegmentoId = 2,
                            Taxa = 0.08m,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 1,
                            ProdutoId = 3,
                            SegmentoId = 3,
                            Taxa = 0.07m,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 1,
                            ProdutoId = 4,
                            SegmentoId = 1,
                            Taxa = 0.20m,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 1,
                            ProdutoId = 4,
                            SegmentoId = 2,
                            Taxa = 0.25m,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 1,
                            ProdutoId = 4,
                            SegmentoId = 3,
                            Taxa = 0.30m,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 2,
                            ProdutoId = 1,
                            SegmentoId = 1,
                            Taxa = 0.06m,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 2,
                            ProdutoId = 1,
                            SegmentoId = 2,
                            Taxa = 0.05m,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 2,
                            ProdutoId = 1,
                            SegmentoId = 3,
                            Taxa = 0.04m,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 13,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 2,
                            ProdutoId = 2,
                            SegmentoId = 1,
                            Taxa = 0.05m,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 14,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 2,
                            ProdutoId = 2,
                            SegmentoId = 2,
                            Taxa = 0.04m,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 15,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 2,
                            ProdutoId = 2,
                            SegmentoId = 3,
                            Taxa = 0.03m,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 16,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 2,
                            ProdutoId = 3,
                            SegmentoId = 1,
                            Taxa = 0.05m,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 17,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 2,
                            ProdutoId = 3,
                            SegmentoId = 2,
                            Taxa = 0.04m,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 18,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 2,
                            ProdutoId = 3,
                            SegmentoId = 3,
                            Taxa = 0.03m,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 19,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 2,
                            ProdutoId = 4,
                            SegmentoId = 1,
                            Taxa = 0.40m,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 20,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 2,
                            ProdutoId = 4,
                            SegmentoId = 2,
                            Taxa = 0.45m,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 21,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 2,
                            ProdutoId = 4,
                            SegmentoId = 3,
                            Taxa = 0.50m,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 22,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 1,
                            ProdutoId = 5,
                            SegmentoId = 4,
                            Taxa = 0.10m,
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 23,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 1,
                            ProdutoId = 5,
                            SegmentoId = 5,
                            Taxa = 0.09m,
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 24,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 1,
                            ProdutoId = 5,
                            SegmentoId = 6,
                            Taxa = 0.08m,
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 25,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 1,
                            ProdutoId = 6,
                            SegmentoId = 4,
                            Taxa = 0.05m,
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 26,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 1,
                            ProdutoId = 6,
                            SegmentoId = 5,
                            Taxa = 0.04m,
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 27,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 1,
                            ProdutoId = 6,
                            SegmentoId = 6,
                            Taxa = 0.03m,
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 28,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 1,
                            ProdutoId = 7,
                            SegmentoId = 4,
                            Taxa = 0.09m,
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 29,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 1,
                            ProdutoId = 7,
                            SegmentoId = 5,
                            Taxa = 0.08m,
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 30,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 1,
                            ProdutoId = 7,
                            SegmentoId = 6,
                            Taxa = 0.07m,
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 31,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 1,
                            ProdutoId = 8,
                            SegmentoId = 4,
                            Taxa = 0.20m,
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 32,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 1,
                            ProdutoId = 8,
                            SegmentoId = 5,
                            Taxa = 0.25m,
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 33,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 1,
                            ProdutoId = 8,
                            SegmentoId = 6,
                            Taxa = 0.30m,
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 34,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 2,
                            ProdutoId = 5,
                            SegmentoId = 4,
                            Taxa = 0.06m,
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 35,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 2,
                            ProdutoId = 5,
                            SegmentoId = 5,
                            Taxa = 0.05m,
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 36,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 2,
                            ProdutoId = 5,
                            SegmentoId = 6,
                            Taxa = 0.04m,
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 37,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 2,
                            ProdutoId = 6,
                            SegmentoId = 4,
                            Taxa = 0.01m,
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 38,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 2,
                            ProdutoId = 6,
                            SegmentoId = 5,
                            Taxa = 0.005m,
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 39,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 2,
                            ProdutoId = 6,
                            SegmentoId = 6,
                            Taxa = 0.005m,
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 40,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 2,
                            ProdutoId = 7,
                            SegmentoId = 4,
                            Taxa = 0.05m,
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 41,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 2,
                            ProdutoId = 7,
                            SegmentoId = 5,
                            Taxa = 0.04m,
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 42,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 2,
                            ProdutoId = 7,
                            SegmentoId = 6,
                            Taxa = 0.03m,
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 43,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 2,
                            ProdutoId = 8,
                            SegmentoId = 4,
                            Taxa = 0.40m,
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 44,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 2,
                            ProdutoId = 8,
                            SegmentoId = 5,
                            Taxa = 0.45m,
                            TipoPessoa = 2
                        },
                        new
                        {
                            Id = 45,
                            Ativo = true,
                            DataAlteracao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modalidade = 2,
                            ProdutoId = 8,
                            SegmentoId = 6,
                            Taxa = 0.50m,
                            TipoPessoa = 2
                        });
                });

            modelBuilder.Entity("SimuladorCredito.Api.Models.Entidades.TaxaCredito", b =>
                {
                    b.HasOne("SimuladorCredito.Api.Models.Entidades.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimuladorCredito.Api.Models.Entidades.Segmento", "Segmento")
                        .WithMany()
                        .HasForeignKey("SegmentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Segmento");
                });
#pragma warning restore 612, 618
        }
    }
}
